---
- import_playbook: 01-common.yml
- import_playbook: 02-containerd.yml
- import_playbook: 03-kubernetes.yml
- import_playbook: 04-cluster.yml
- import_playbook: 05-calico.yml
- import_playbook: 06-metallb.yml